app: fly-image-playground
config:
  "STATIC_FILES_BASE_FOLDER": "client/build"
files:
  - client/build/index.html
  - client/build/static/js/main.ff4d387e.js
  - client/build/static/js/main.ff4d387e.js.map
  - client/build/static/css/main.11c6a295.css
  - client/build/static/css/main.11c6a295.css.map
  - client/build/asset-manifest.json
  - client/build/favicon.ico
  - client/build/manifest.json
  - client/build/service-worker.js